spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: MyAwesomeBackend
server:
  port: 8081
app:
  name: MyAwesomeBackend